name = "qafiyah-api"
main = "src/app.ts"
compatibility_date = "2025-04-09"

compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true