name: Post Poem

on:
  schedule:
    - cron: "*/29 * * * *" # Every 29 minutes (~50 times/day)
  workflow_dispatch:

jobs:
  tweet:
    name: 🐦 Post Poem to Twitter
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 🔧 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 🔄 Setup pnpm cache
        id: pnpm-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 📥 Install dependencies
        # Remove the --frozen-lockfile flag to allow installation without a lockfile
        run: pnpm install

      - name: 🏗️ Build bot directly
        run: |
          cd apps/bot
          pnpm build

      - name: 🚀 Run bot
        env:
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: |
          cd apps/bot
          pnpm start
